import type { Metadata } from "next";
import "./globals.scss";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import { CSSProperties } from "react";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import ReactLenis from "lenis/react";

const gt = localFont({
  src: [
    {
      path: "../fonts/goodtiming.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const os = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vir2al Verse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
        style={
          {
            "--fontH": gt.style.fontFamily,
            "--fontP": os.style.fontFamily,
          } as CSSProperties
        }
      >
        <ReactLenis root>
          <Header />
          {children}
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
